/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author estma_000
 */

import controladores.Descifrar;
import controladores.CrearLlaves;
import vistas.inner.expansionDES;
import vistas.VistaDescifrar;
import vistas.inner.Permutacion;
import vistas.inner.S_BoxDES;

public class InnerDESDes extends javax.swing.JDialog {

    /**
     * Creates new form InnerDESDes
     */
    private String ki;
    private String Ri1;
    private String Ei;
    
    public InnerDESDes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        elegirStrings();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        expansion = new javax.swing.JButton();
        tablas = new javax.swing.JButton();
        permutacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setText("El resultado del S-Box pasa por una permutación final");

        jLabel7.setText("Se recibe k = " + ki);

        expansion.setText("Expansión");
        expansion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expansionActionPerformed(evt);
            }
        });

        tablas.setText("Tabla S-Box");
        tablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablasActionPerformed(evt);
            }
        });

        permutacion.setText("Permutación");
        permutacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permutacionActionPerformed(evt);
            }
        });

        jLabel1.setText("Se recibe la Ri-1 = " + Ri1);

        jLabel2.setText("La cual debe ser expandida usando la función de expansión");

        jLabel3.setText("Queda E = " + Ei);

        jLabel4.setText("Se hace una operación XOR entre E y Ri-1, y esto pasa por un S-Box");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inner_DES.PNG"))); // NOI18N

        atras.setText("Atras");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(atras)
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(expansion))
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tablas))
                        .addComponent(jLabel7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(permutacion))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(633, Short.MAX_VALUE)
                .addComponent(atras)
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(expansion))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(tablas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel5)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(permutacion))
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void expansionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expansionActionPerformed
        // TODO add your handling code here:
        new expansionDES(this, true).setVisible(true);
    }//GEN-LAST:event_expansionActionPerformed

    private void tablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablasActionPerformed
        // TODO add your handling code here:
        new S_BoxDES(this, true).setVisible(true);
    }//GEN-LAST:event_tablasActionPerformed

    private void permutacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permutacionActionPerformed
        // TODO add your handling code here:
        new Permutacion(this, true).setVisible(true);
    }//GEN-LAST:event_permutacionActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InnerDESDes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InnerDESDes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InnerDESDes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InnerDESDes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InnerDESDes dialog = new InnerDESDes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton expansion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton permutacion;
    private javax.swing.JButton tablas;
    // End of variables declaration//GEN-END:variables

    private void elegirStrings(){
        switch(VistaDescifrar.numeroF){
            case 1:
                Ri1 = Descifrar.R0.toString();
                ki = CrearLlaves.k1.toString();
                Ei = Descifrar.E1.toString();
            break;
            case 2:
                Ri1 = Descifrar.R1.toString();
                ki = CrearLlaves.k2.toString();
                Ei = Descifrar.E2.toString();
            break;
            case 3:
                Ri1 = Descifrar.R2.toString();
                ki = CrearLlaves.k3.toString();
                Ei = Descifrar.E3.toString();
            break;
            case 4:
                Ri1 = Descifrar.R3.toString();
                ki = CrearLlaves.k4.toString();
                Ei = Descifrar.E4.toString();
            break;
            case 5:
                Ri1 = Descifrar.R4.toString();
                ki = CrearLlaves.k5.toString();
                Ei = Descifrar.E5.toString();
            break;
            case 6:
                Ri1 = Descifrar.R5.toString();
                ki = CrearLlaves.k6.toString();
                Ei = Descifrar.E6.toString();
            break;
            case 7:
                Ri1 = Descifrar.R6.toString();
                ki = CrearLlaves.k7.toString();
                Ei = Descifrar.E7.toString();
            break;
            case 8:
                Ri1 = Descifrar.R7.toString();
                ki = CrearLlaves.k8.toString();
                Ei = Descifrar.E8.toString();
            break;
            case 9:
                Ri1 = Descifrar.R8.toString();
                ki = CrearLlaves.k9.toString();
                Ei = Descifrar.E9.toString();
            break;
            case 10:
                Ri1 = Descifrar.R9.toString();
                ki = CrearLlaves.k10.toString();
                Ei = Descifrar.E10.toString();
            break;
            case 11:
                Ri1 = Descifrar.R10.toString();
                ki = CrearLlaves.k11.toString();
                Ei = Descifrar.E11.toString();
            break;
            case 12:
                Ri1 = Descifrar.R11.toString();
                ki = CrearLlaves.k12.toString();
                Ei = Descifrar.E12.toString();
            break;
            case 13:
                Ri1 = Descifrar.R12.toString();
                ki = CrearLlaves.k13.toString();
                Ei = Descifrar.E13.toString();
            break;
            case 14:
                Ri1 = Descifrar.R13.toString();
                ki = CrearLlaves.k14.toString();
                Ei = Descifrar.E14.toString();
            break;
            case 15:
                Ri1 = Descifrar.R14.toString();
                ki = CrearLlaves.k15.toString();
                Ei = Descifrar.E15.toString();
            break;
            case 16:
                Ri1 = Descifrar.R15.toString();
                ki = CrearLlaves.k16.toString();
                Ei = Descifrar.E16.toString();
            break;
            
        }
    }}
