/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.CrearLlaves;
import java.util.ArrayList;

/**
 *
 * @author estma_000
 */
public class PermutationC_2 extends javax.swing.JDialog {

    /**
     * Creates new form PermutationC_2
     */
    
    private ArrayList<Integer> di;
    private ArrayList<Integer> di1;
    private ArrayList<Integer> ci;
    private ArrayList<Integer> ci1;
    
    public PermutationC_2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        elegirStrings();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PC-2");

        jLabel1.setText("En la iteración " + VistaCifrar.numeroK + "se tiene C = " + ci + " y D = " + di);

        jLabel2.setText("Con ayuda de la siguiente permutacion se obtienen las siguientes partes de la llave");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PC_2.png"))); // NOI18N

        jLabel4.setText("La salida para C es " + ci1 + " y la salida para D es " + di1);

        atras.setText("Atras");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(atras))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addComponent(atras)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PermutationC_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PermutationC_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PermutationC_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PermutationC_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PermutationC_2 dialog = new PermutationC_2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
    private void elegirStrings (){
        switch(VistaCifrar.numeroK){
            case 1:
                ci = CrearLlaves.c0;
                ci1 = CrearLlaves.c1;
                di = CrearLlaves.d0;
                di1 = CrearLlaves.d1;
                break;
            case 2:
                ci = CrearLlaves.c1;
                ci1 = CrearLlaves.c2;
                di = CrearLlaves.d1;
                di1 = CrearLlaves.d2;
                break;
            case 3:
                ci = CrearLlaves.c2;
                ci1 = CrearLlaves.c3;
                di = CrearLlaves.d2;
                di1 = CrearLlaves.d3;
                break;
            case 4:
                ci = CrearLlaves.c3;
                ci1 = CrearLlaves.c4;
                di = CrearLlaves.d3;
                di1 = CrearLlaves.d4;
                break;
            case 5:
                ci = CrearLlaves.c4;
                ci1 = CrearLlaves.c5;
                di = CrearLlaves.d4;
                di1 = CrearLlaves.d5;
                break;
            case 6:
                ci = CrearLlaves.c5;
                ci1 = CrearLlaves.c6;
                di = CrearLlaves.d5;
                di1 = CrearLlaves.d6;
                break;
            case 7:
                ci = CrearLlaves.c6;
                ci1 = CrearLlaves.c7;
                di = CrearLlaves.d6;
                di1 = CrearLlaves.d7;
                break;
            case 8:
                ci = CrearLlaves.c7;
                ci1 = CrearLlaves.c8;
                di = CrearLlaves.d7;
                di1 = CrearLlaves.d8;
                break;
            case 9:
                ci = CrearLlaves.c8;
                ci1 = CrearLlaves.c9;
                di = CrearLlaves.d8;
                di1 = CrearLlaves.d9;
                break;
            case 10:
                ci = CrearLlaves.c9;
                ci1 = CrearLlaves.c10;
                di = CrearLlaves.d9;
                di1 = CrearLlaves.d10;
                break;
            case 11:
                ci = CrearLlaves.c10;
                ci1 = CrearLlaves.c11;
                di = CrearLlaves.d10;
                di1 = CrearLlaves.d11;
                break;
            case 12:
                ci = CrearLlaves.c11;
                ci1 = CrearLlaves.c12;
                di = CrearLlaves.d11;
                di1 = CrearLlaves.d12;
                break;
            case 13:
                ci = CrearLlaves.c12;
                ci1 = CrearLlaves.c13;
                di = CrearLlaves.d12;
                di1 = CrearLlaves.d13;
                break;
            case 14:
                ci = CrearLlaves.c13;
                ci1 = CrearLlaves.c14;
                di = CrearLlaves.d13;
                di1 = CrearLlaves.d14;
                break;
            case 15:
                ci = CrearLlaves.c14;
                ci1 = CrearLlaves.c15;
                di = CrearLlaves.d14;
                di1 = CrearLlaves.d15;
                break;
            case 16:
                ci = CrearLlaves.c15;
                ci1 = CrearLlaves.c16;
                di = CrearLlaves.d15;
                di1 = CrearLlaves.d16;
                break;
        
        }
    }
}
