/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.Cifrar;

/**
 *
 * @author estma_000
 */

public class VistaCifrar extends javax.swing.JFrame {

    /**
     * Creates new form VistaCifrar
     */
    
    public Cifrar cifrar;
    public static int numeroK = 0;
    
    public VistaCifrar() {
        cifrar = new Cifrar(Principal.texto, Principal.llave);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        k1 = new javax.swing.JButton();
        k2 = new javax.swing.JButton();
        k3 = new javax.swing.JButton();
        k4 = new javax.swing.JButton();
        k5 = new javax.swing.JButton();
        k6 = new javax.swing.JButton();
        k7 = new javax.swing.JButton();
        k8 = new javax.swing.JButton();
        k9 = new javax.swing.JButton();
        k10 = new javax.swing.JButton();
        k11 = new javax.swing.JButton();
        k12 = new javax.swing.JButton();
        k13 = new javax.swing.JButton();
        k14 = new javax.swing.JButton();
        k15 = new javax.swing.JButton();
        k16 = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        PC_1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Proceso Cifrado");
        setPreferredSize(new java.awt.Dimension(400, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DES_Schema.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        k1.setText("k1");
        k1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k1ActionPerformed(evt);
            }
        });
        getContentPane().add(k1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 50, -1));

        k2.setText("k2");
        getContentPane().add(k2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 50, -1));

        k3.setText("k3");
        getContentPane().add(k3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 50, -1));

        k4.setText("k4");
        k4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k4ActionPerformed(evt);
            }
        });
        getContentPane().add(k4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 50, -1));

        k5.setText("k5");
        getContentPane().add(k5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 50, -1));

        k6.setText("k6");
        getContentPane().add(k6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 50, -1));

        k7.setText("k7");
        getContentPane().add(k7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 50, -1));

        k8.setText("k8");
        getContentPane().add(k8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 50, -1));

        k9.setText("k9");
        getContentPane().add(k9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 50, -1));

        k10.setText("k10");
        getContentPane().add(k10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        k11.setText("k11");
        getContentPane().add(k11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        k12.setText("k12");
        getContentPane().add(k12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        k13.setText("k13");
        getContentPane().add(k13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        k14.setText("k14");
        getContentPane().add(k14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        k15.setText("k15");
        getContentPane().add(k15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));

        k16.setText("k16");
        getContentPane().add(k16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, -1, -1));

        atras.setText("Atras");
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 100, -1));

        PC_1.setText("PC-1");
        PC_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PC_1ActionPerformed(evt);
            }
        });
        getContentPane().add(PC_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void k1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k1ActionPerformed
        // TODO add your handling code here:
        numeroK = 1;   
        new PermutationC_2(this, true).setVisible(true);
    }//GEN-LAST:event_k1ActionPerformed

    private void k4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k4ActionPerformed

    private void PC_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PC_1ActionPerformed
        // TODO add your handling code here:
        new PermutationC_1(this, true).setVisible(true);
    }//GEN-LAST:event_PC_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCifrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCifrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCifrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCifrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCifrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PC_1;
    private javax.swing.JButton atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton k1;
    private javax.swing.JButton k10;
    private javax.swing.JButton k11;
    private javax.swing.JButton k12;
    private javax.swing.JButton k13;
    private javax.swing.JButton k14;
    private javax.swing.JButton k15;
    private javax.swing.JButton k16;
    private javax.swing.JButton k2;
    private javax.swing.JButton k3;
    private javax.swing.JButton k4;
    private javax.swing.JButton k5;
    private javax.swing.JButton k6;
    private javax.swing.JButton k7;
    private javax.swing.JButton k8;
    private javax.swing.JButton k9;
    // End of variables declaration//GEN-END:variables
}
